# Generated by Django 4.1.7 on 2023-03-31 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название категории')),
            ],
            options={
                'verbose_name': 'Категория мебели',
                'verbose_name_plural': 'Категории мебели',
            },
        ),
        migrations.CreateModel(
            name='Partner',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название партнёра')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Логотип партнера')),
                ('link', models.CharField(blank=True, max_length=200, null=True, verbose_name='Ссылка на сайт партнера')),
            ],
            options={
                'verbose_name': 'Партнёр',
                'verbose_name_plural': 'Партнёры',
            },
        ),
        migrations.CreateModel(
            name='Reviews',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('image', models.ImageField(blank=True, null=True, upload_to='reviews')),
                ('text', models.TextField(verbose_name='отзывы')),
            ],
            options={
                'verbose_name': 'Отзывы',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='Furniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Название мебели')),
                ('image', models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Картинка мебели')),
                ('price', models.CharField(max_length=200, verbose_name='Цена')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='category_furniture', to='mebel.furniturecategory', verbose_name='Категория мебели')),
            ],
            options={
                'verbose_name': 'Мебель',
                'verbose_name_plural': 'Мебель',
            },
        ),
    ]
