# Generated by Django 4.1.7 on 2023-03-31 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniture',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название мебели'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название мебели'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название мебели'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
        migrations.AddField(
            model_name='partner',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название партнёра'),
        ),
    ]
