# Generated by Django 4.1.7 on 2023-04-15 11:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0002_furniture_title_en_furniture_title_ky_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='furniturecategory',
            name='title_en',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='furniturecategory',
            name='title_ky',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
        migrations.AddField(
            model_name='furniturecategory',
            name='title_ru',
            field=models.CharField(max_length=200, null=True, verbose_name='Название категории'),
        ),
    ]
