# Generated by Django 4.1.7 on 2023-04-15 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0003_furniturecategory_title_en_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FurnitureFullDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('furniture', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='furniture_descriptions', to='mebel.furniture')),
            ],
            options={
                'verbose_name': 'Описание мебели',
                'ordering': ['text'],
            },
        ),
    ]
