# Generated by Django 4.1.7 on 2023-04-24 18:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0004_furniturefulldescription'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contacts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(blank=True, max_length=500, null=True)),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('vk', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.CreateModel(
            name='DescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image_1', models.FileField(blank=True, null=True, upload_to='desc_image')),
                ('image_2', models.FileField(blank=True, null=True, upload_to='desc_image')),
                ('image_3', models.FileField(blank=True, null=True, upload_to='desc_image')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекция',
            },
        ),
        migrations.CreateModel(
            name='ItemsFurniture',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_1', models.FileField(blank=True, null=True, upload_to='collection')),
                ('item_2', models.FileField(blank=True, null=True, upload_to='collection')),
                ('item_3', models.FileField(blank=True, null=True, upload_to='collection')),
                ('item_4', models.FileField(blank=True, null=True, upload_to='collection')),
                ('item_5', models.FileField(blank=True, null=True, upload_to='collection')),
                ('item_6', models.FileField(blank=True, null=True, upload_to='collection')),
            ],
            options={
                'verbose_name': 'Коллекция',
                'verbose_name_plural': 'Коллекция',
            },
        ),
        migrations.CreateModel(
            name='Logo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('logo', models.FileField(blank=True, null=True, upload_to='logo')),
            ],
            options={
                'verbose_name': 'Логотип',
                'verbose_name_plural': 'Логотип',
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Новости')),
                ('date', models.DateField(auto_now_add=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='news')),
            ],
            options={
                'verbose_name': 'Новости',
                'ordering': ['title'],
            },
        ),
        migrations.AddField(
            model_name='furniture',
            name='status',
            field=models.CharField(choices=[('new', 'new'), ('sale', 'sale'), ('old', 'old')], default=1, max_length=4),
            preserve_default=False,
        ),
        migrations.CreateModel(
            name='NewsFullDescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст')),
                ('news', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='news_descriptions', to='mebel.news')),
            ],
            options={
                'verbose_name': 'Описание_новостей',
                'ordering': ['text'],
            },
        ),
    ]
