# Generated by Django 4.1.7 on 2023-04-24 19:05

import ckeditor.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0005_contacts_descriptionimage_itemsfurniture_logo_news_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contacts', ckeditor.fields.RichTextField(verbose_name='Контакты')),
                ('email', models.CharField(blank=True, max_length=100, null=True)),
                ('instagram', models.CharField(blank=True, max_length=100, null=True)),
                ('whatsapp', models.CharField(blank=True, max_length=100, null=True)),
                ('facebook', models.CharField(blank=True, max_length=100, null=True)),
                ('twitter', models.CharField(blank=True, max_length=100, null=True)),
                ('vk', models.CharField(blank=True, max_length=100, null=True)),
            ],
            options={
                'verbose_name': 'Контакты',
                'verbose_name_plural': 'Контакты',
            },
        ),
        migrations.DeleteModel(
            name='Contacts',
        ),
        migrations.RemoveField(
            model_name='newsfulldescription',
            name='news',
        ),
        migrations.RemoveField(
            model_name='furniture',
            name='image',
        ),
        migrations.AddField(
            model_name='furniture',
            name='desc',
            field=ckeditor.fields.RichTextField(default=1, verbose_name='Описание'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_1',
            field=models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Первая картинка'),
        ),
        migrations.AddField(
            model_name='furniture',
            name='image_2',
            field=models.ImageField(blank=True, null=True, upload_to='partner-image', verbose_name='Вторая картинка'),
        ),
        migrations.AddField(
            model_name='news',
            name='desc',
            field=ckeditor.fields.RichTextField(default=111, verbose_name='Текст новости'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='reviews',
            name='position',
            field=models.CharField(blank=True, max_length=200, null=True, verbose_name='Должность'),
        ),
        migrations.AlterField(
            model_name='furniture',
            name='price',
            field=models.DecimalField(decimal_places=2, max_digits=50, verbose_name='Цена'),
        ),
        migrations.DeleteModel(
            name='FurnitureFullDescription',
        ),
        migrations.DeleteModel(
            name='NewsFullDescription',
        ),
    ]
