# Generated by Django 4.1.7 on 2023-04-24 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mebel', '0006_contact_delete_contacts_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Email',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('address', models.CharField(max_length=200, verbose_name='Почта клиентов')),
            ],
            options={
                'verbose_name': 'Почтовые адреса',
                'verbose_name_plural': 'Почтовые адреса',
            },
        ),
    ]
